### ISSUE TITLE
Get enum WaylandProtocolEvent in the event loop

### ISSUE THREAD

**Issue by vohebup** [vberger/wayland-client-rs#24]
Is it possible to receive events without enum [`Event`](https://vberger.github.io/wayland-client-rs/wayland_client/enum.Event.html)? It would be ideal to rename [`WaylandProtocolEvent`](https://vberger.github.io/wayland-client-rs/wayland_client/wayland/enum.WaylandProtocolEvent.html) to `Event` and get it in the event loop.

**Comment by vberger** [comment]
The enum `Event` is here for future-proofing.

In mid term future, I plan to integrate protocols extensions such a `xdg_shell` (which is destined to replace the current `wl_shell` interface). And it will sit alongside the wayland protocol, so the `Event` enum will look like:

```rust
pub enum Event {
    Wayland(WaylandProtocolEvent),
    XdgShell(SdgShellProtocolEvent),
}
```

And then other protocols will probably be added.

For now, you can quickly unwrap one level of this enum using code such as
```rust
let Event::Wayland(evt) = evt;
```
to rebind the `evt` variable to the contents of the enum. Note however that such code will break as soon as a second protocol is added.

**Comment by vohebup** [comment]
Maybe better on a callback? And then in addition hdg_shell can invent something, and the bindings of the possible range of received events (`Event`) it will be impossible to expand without changing the source code.

**Comment by vberger** [comment]
I've explicitly moved away from callbacks (which is the default behaviour of wayland) to iterators because the latter behave much more smoothly with Rust's type system than the former, so I don't plan to come back to callbacks.

Also, protocol extensions explicitly interact pretty tightly with the core protocol, so having them in other crates will hardly be possible without making the whole thing pretty unsafe and error-prone. My aim is to integrate other protocols into this crate as well, under the form of cargo features.

**Comment by vohebup** [comment]
In version 0.2 of the bindings to change the object in the closure of the callback, I had to actively use mutexes, the latest version uses queuing with `match` and the objects are borrowed automatically and mutexes are not needed. What is the lesser evil? Maybe there's a way to do it without mutexes, but it is faster than the queue?

Assume that library wayland-client rewrite to rust and distribute it as a dynamic library. Does this mean I would have to using rust bindings to rust library?

Whether there is overhead when converting `i32` to `int32_t`

**Comment by vberger** [comment]
Actually, it's not possible to rewrite the wayland-client binary library in rust and use it in production, because OpenGL implementations are directly linked to the C library and expect it to be the one in use. Replacing it with a Rust implementation would mean mimicking the internal structure of the C lib, which makes the whole thing useless.

The changes from callbacks to iterators was indeed meant to avoir this Arc & Mutex hell, that is absolutely not necessary. And anyway performances should not be an issue at all, the load caused by the communication between client & server is very low.

However, which objects are you talking about regarding them being borrowed automatically ? The `EventIterator` does not borrow anything...

**Comment by vohebup** [comment]
If catch-up to mimic, then needed a Rast in system programming where the range of C ABI? In order to make a dynamic library, you must write extern and sometimes to reflect: and do I adhere to ideologies C? Builders, enum of tuples, etc.

Well, not exactly borrowing: eventloop is single-threaded, and upon receiving the event executes 1 branch `match` in which sequentially modified wayland object: be it a change in the position of the surface, attaching the buffer, causing damage, etc. Now, if it were possible to transfer this warranty on callbacks..

**Comment by vberger** [comment]
You can build a system of callbacks, but it'll force you to have a huge lot of `Arc`s and `Mutex`es.

But you can also split your logic using several `EventIterator`s. You can change the iterator associated with a wayland object using `.set_evt_iterator()` of the `Proxy` trait, which lets you have as much granularity as you want (and multithreading, if that is your goal).

**Comment by vohebup** [comment]
`Arc` & `Mutex` hell will be only when we want to modify the object from another thread. In other cases, you can use `Rc`. I understand that the code will be a little prettier if you use a queue instead of callbacks. But the bindings to the system library - one way or another they will be as part of something larger.

**Comment by vberger** [comment]
No, you won't be able to use `Rc`. Because to ensure thread-safety, I *must* put `Send + Sync` bounds on the closures, and `Rc` is neither `Send` nor `Sync`.

Using an iterator-based approach allows me to align in behaviour with other crates, and is much more friendly to the borrow-checker and the way rust programs are built in general.

And due to the design of the wayland-client C library, it is not possible for me to offer both an iterator interface and a callback interface.
